rolf:
  name: bc
  max_global_step: 50
  warm_up_steps: 0
  train_every: 0
  log_every: 1
  evaluate_every: 1
  ckpt_every: 10
  reward_scale: 1.0
  batch_size: 64
  ob_norm: false
  max_ob_norm_step: 100000000
  clip_obs: .inf
  clip_range: 10
  policy_mlp_dim:
  - 512
  - 256
  - 256
  policy_activation: relu
  tanh_policy: true
  gaussian_policy: false
  actor_lr: 0.0003
  actor_weight_decay: 0
  min_std: 1.0e-10
  max_std: 2
  use_log_std_bias: false
  target_init_std: 0.5
  encoder_type: resnet18
  encoder_image_size:
  - 224
  - 224
  encoder_conv_dim: 32
  encoder_kernel_size:
  - 3
  - 3
  - 3
  - 3
  encoder_stride:
  - 2
  - 1
  - 1
  - 1
  encoder_conv_output_dim: 50
  encoder_soft_update_weight: 0.95
  asym_ac: false
  demo_path: demonstration/stool_processed/
  demo_low_level: false
  demo_subsample_interval: 1
  demo_sample_range:
  - 0.0
  - 1.0
  data_path: null
  num_eval: 50
  bc_lr: 0.0003
  val_split: 0.05
  normalizer: bn
  rnn: false
  rnn_hidden_size: 1024
  rnn_num_layers: 2
  seq_len: 10
  num_demos: null
  encoder: null
  finetune_encoder: true
  device: cuda
  image_agmt: false
  rotation: quaternion
  precision: 32
  is_train: true
env:
  id: FurnitureDummy-v0
  screen_size:
  - 512
  - 512
  action_repeat: 1
  absorbing_state: false
  pixel_ob: false
  state_ob: true
  furniture: stool
  record: false
  use_all_cam: false
  randomness: low
  from_skill: 0
  skill: -1
  high_random_idx: 0
  channel_first: true
  np_step_out: true
  concat_robot_state: true
num_threads: 8
seed: 123
is_train: true
init_ckpt_path: null
init_ckpt_pretrained: false
init_ckpt_dir: checkpoints/ckpt
gpu: 0
device: cuda
precision: 32
ckpt_num: null
num_eval: 1
record_video: false
record_video_caption: true
record_demo: false
run_prefix: stool_full_bc_resnet18_low
notes: null
log_root_dir: log
wandb: false
wandb_entity: clvr
wandb_project: furniture-bench
run_name: FurnitureDummy-v0.bc.stool_full_bc_resnet18_low.123
log_dir: log/FurnitureDummy-v0.bc.stool_full_bc_resnet18_low.123
video_dir: log/FurnitureDummy-v0.bc.stool_full_bc_resnet18_low.123/video
demo_dir: log/FurnitureDummy-v0.bc.stool_full_bc_resnet18_low.123/demo
ckpt_dir: log/FurnitureDummy-v0.bc.stool_full_bc_resnet18_low.123/ckpt
replay_dir: log/FurnitureDummy-v0.bc.stool_full_bc_resnet18_low.123/replay
rank: 0
is_chef: true
num_workers: 1
